#!/bin/sh
# Tests for the watcher auto-update logic (watcher_lib.sh: read_options,
# provider_src, fetch_latest, and fetch_monochrome) generated by
# scripts/install_watcher_addon.sh.
#
# Run from the repo root:   sh tests/test_watcher_autoupdate.sh
#
# Generating the add-on downloads the provider from GitHub; if that fails
# (offline) the whole suite auto-skips. Set SKIP_NETWORK_TESTS=1 to skip.

set -u
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/install_watcher_addon.sh"
PASS=0; FAIL=0; SKIP=0
red(){ printf '\033[31m%s\033[0m' "$*"; }; green(){ printf '\033[32m%s\033[0m' "$*"; }; yellow(){ printf '\033[33m%s\033[0m' "$*"; }
pass(){ PASS=$((PASS+1)); printf '  %s %s\n' "$(green PASS)" "$1"; }
fail(){ FAIL=$((FAIL+1)); printf '  %s %s\n' "$(red FAIL)" "$1"; [ -n "${2:-}" ] && printf '       %s\n' "$2"; }
skip(){ SKIP=$((SKIP+1)); printf '  %s %s\n' "$(yellow SKIP)" "$1"; }
assert_eq(){ if [ "$2" = "$3" ]; then pass "$1"; else fail "$1" "expected: $2 / actual: $3"; fi; }

# sha256sum shim for macOS (Alpine, where the add-on runs, has it natively)
if ! command -v sha256sum >/dev/null 2>&1 && command -v shasum >/dev/null 2>&1; then
    SHIM="$(mktemp -d)"; printf '#!/bin/sh\nexec shasum -a 256 "$@"\n' > "$SHIM/sha256sum"
    chmod +x "$SHIM/sha256sum"; PATH="$SHIM:$PATH"
fi

TMP_ADDONS="$(mktemp -d)"
if [ "${SKIP_NETWORK_TESTS:-0}" = "1" ] || ! sh "$SCRIPT" --force \
        --addons-dir "$TMP_ADDONS" --ma-id addon_test --python-version python3.14 >/dev/null 2>&1; then
    skip "could not generate add-on (offline or skipped) -- auto-update tests skipped"
    printf '\n== Summary ==\n  passed: %s\n  failed: %s\n  skipped: %s\n' "$PASS" "$FAIL" "$SKIP"
    exit 0
fi
ADDON="$TMP_ADDONS/ma_provider_watcher"
LIB="$ADDON/watcher_lib.sh"; RUNSH="$ADDON/run.sh"

# --- syntax ---
bash -n "$RUNSH" 2>/dev/null && pass "run.sh parses" || fail "run.sh parses"
bash -n "$LIB" 2>/dev/null && pass "watcher_lib.sh parses" || fail "watcher_lib.sh parses"
if command -v shellcheck >/dev/null 2>&1; then
    # Lint both generated files, excluding SC2034 only: run.sh sets
    # provider paths/URLs that are used by the sourced lib, and the lib sets
    # runtime options used by run.sh, so each looks "unused"
    # when the files are analysed separately. Every other check still applies.
    # (-x source-following behaves differently across shellcheck versions -- e.g.
    # CI's 0.9.0 -- so exclude the one check that can't work per-file instead.)
    sc_out="$(shellcheck -S warning -e SC2034 "$RUNSH" "$LIB" 2>&1)" \
        && pass "shellcheck clean (generated run.sh + lib)" \
        || fail "shellcheck reported issues" "$sc_out"
else
    skip "shellcheck not installed"
fi

# --- read_options (the blocker + clamp) ---
# read_options parses /data/options.json with jq (installed in the add-on image).
# On a runner without jq the parse degrades every input to the defaults, so skip
# these assertions rather than emit misleading failures (mirrors the sha256sum
# shim above; the alpine CI job installs jq so it exercises them for real).
if command -v jq >/dev/null 2>&1; then
    opt(){ printf '%s' "$1" > "$TMP_ADDONS/o.json"; ( . "$LIB"; read_options "$TMP_ADDONS/o.json"; printf '%s|%s|%s|%s|%s|%s|%s' "$YTMUSIC_AUTO_UPDATE" "$MONOCHROME_AUTO_UPDATE" "$UPDATE_INTERVAL_HOURS" "$MONOCHROME_ENABLED" "$GITHUB_TOKEN" "$YTMUSIC_ACTIVE_VERSION" "$MONOCHROME_ACTIVE_VERSION" ); }
    assert_eq "both provider updates default off" "false|false|24|true||current|current" "$(opt '{}')"
    assert_eq "YouTube update can be enabled independently" \
        "true|false|24|true||current|current" "$(opt '{"ytmusic_auto_update":true,"monochrome_auto_update":false}')"
    assert_eq "Monochrome update can be enabled independently" \
        "false|true|24|true||current|current" "$(opt '{"ytmusic_auto_update":false,"monochrome_auto_update":true}')"
    assert_eq "legacy auto_update:true migrates both providers to on" \
        "true|true|24|true||current|current" "$(opt '{"auto_update":true}')"
    assert_eq "new explicit false overrides legacy true" \
        "false|true|24|true||current|current" "$(opt '{"auto_update":true,"ytmusic_auto_update":false}')"
    assert_eq "interval 0 clamps to 1"        "true|true|1|true||current|current"   "$(opt '{"auto_update":true,"update_interval_hours":0}')"
    assert_eq "interval negative clamps to 1" "true|true|1|true||current|current"   "$(opt '{"auto_update":true,"update_interval_hours":-5}')"
    assert_eq "interval non-numeric -> 24"    "true|true|24|true||current|current"  "$(opt '{"auto_update":true,"update_interval_hours":"x"}')"
    assert_eq "interval null -> 24"           "true|true|24|true||current|current"  "$(opt '{"auto_update":true,"update_interval_hours":null}')"
    assert_eq "interval 168 kept"             "true|true|168|true||current|current" "$(opt '{"auto_update":true,"update_interval_hours":168}')"
    assert_eq "Monochrome settings parse token and explicit false" \
        "false|false|24|false|test-token|current|current" \
        "$(opt '{"monochrome_enabled":false,"github_token":"test-token"}')"
    assert_eq "active version selectors parse Previous independently" \
        "false|false|24|true||previous|current" \
        "$(opt '{"ytmusic_active_version":"previous","monochrome_active_version":"invalid"}')"
else
    skip "jq not installed -- read_options assertions skipped"
fi

# --- provider_src precedence + fetch_latest change detection ---
W="$(mktemp -d)"
result="$(
    . "$LIB"
    YTMUSIC_AUTO_UPDATE=true
    CACHE="$W/cache"; BUNDLED="$W/bundled"; HASHFILE="$W/hash"; DATEFILE="$W/date"
    PREVIOUS_CACHE="$W/cache.previous"; PREVIOUS_HASHFILE="$W/hash.previous"; PREVIOUS_DATEFILE="$W/date.previous"
    mkdir -p "$BUNDLED"; echo bundled > "$BUNDLED/x"
    src1="$(provider_src)"                                   # no cache -> bundled
    mkdir -p "$W/ytmusic_free"; echo v1 > "$W/ytmusic_free/__init__.py"; echo '{}' > "$W/ytmusic_free/manifest.json"
    ( cd "$W" && tar -czf pkg.tgz ytmusic_free )
    TARBALL_URL="file://$W/pkg.tgz"
    fetch_latest >/dev/null 2>&1; r1=$?                      # new -> 0
    src2="$(provider_src)"                                   # auto-update on + cache -> cache
    # Disabling updates pins the current cache; slot selection controls rollback.
    YTMUSIC_AUTO_UPDATE=false; src_off="$(provider_src)"; YTMUSIC_AUTO_UPDATE=true
    fetch_latest >/dev/null 2>&1; r2=$?                      # unchanged -> 2
    echo v2 > "$W/ytmusic_free/__init__.py"; ( cd "$W" && tar -czf pkg.tgz ytmusic_free )
    fetch_latest >/dev/null 2>&1; r3=$?                      # changed -> 0
    YTMUSIC_ACTIVE_VERSION=previous; src_previous="$(provider_src)"
    previous_value="$(cat "$PREVIOUS_CACHE/__init__.py")"
    rm "$W/ytmusic_free/manifest.json"; ( cd "$W" && tar -czf pkg.tgz ytmusic_free )
    fetch_latest >/dev/null 2>&1; r4=$?                      # invalid -> 1, slots untouched
    current_value="$(cat "$CACHE/__init__.py")"
    [ "$src1" = "$BUNDLED" ] && [ "$src2" = "$CACHE" ] && [ "$src_off" = "$CACHE" ] \
        && [ "$src_previous" = "$PREVIOUS_CACHE" ] && [ "$previous_value" = v1 ] \
        && [ "$current_value" = v2 ] && [ -s "$PREVIOUS_HASHFILE" ] \
        && [ -s "$PREVIOUS_DATEFILE" ] && echo "$r1 $r2 $r3 $r4"
)"
assert_eq "slots rotate v1 to Previous and reject invalid update = 0/2/0/1" "0 2 0 1" "$result"

# --- private Monochrome cache + token handling ---
mono_result="$(
    . "$LIB"
    MONOCHROME_ENABLED=true
    MONOCHROME_ACTIVE_VERSION=current
    MONOCHROME_CACHE="$W/mono-cache"; MONOCHROME_HASHFILE="$W/mono-hash"; MONOCHROME_DATEFILE="$W/mono-date"
    MONOCHROME_PREVIOUS_CACHE="$W/mono-cache.previous"; MONOCHROME_PREVIOUS_HASHFILE="$W/mono-hash.previous"; MONOCHROME_PREVIOUS_DATEFILE="$W/mono-date.previous"
    mkdir -p "$W/monochrome"; echo mono-v1 > "$W/monochrome/__init__.py"; echo '{}' > "$W/monochrome/manifest.json"
    ( cd "$W" && tar -czf mono.tgz monochrome )
    MONOCHROME_TARBALL_URL="file://$W/mono.tgz"
    GITHUB_TOKEN="private-token-must-not-leak"
    fetch_out="$(fetch_monochrome 2>&1)"; r1=$?
    src1="$(monochrome_src)"
    fetch_monochrome >/dev/null 2>&1; r2=$?
    GITHUB_TOKEN=""
    fetch_monochrome >/dev/null 2>&1; r3=$?
    MONOCHROME_ENABLED=false; src_off="$(monochrome_src)"
    leaked=no
    if printf '%s' "$fetch_out" | grep -q 'private-token-must-not-leak'; then leaked=yes; fi
    [ "$src1" = "$MONOCHROME_CACHE" ] && [ -z "$src_off" ] \
        && printf '%s %s %s %s' "$r1" "$r2" "$r3" "$leaked"
)"
assert_eq "Monochrome fetch new/unchanged/missing-token = 0/2/1 and token is not logged" \
    "0 2 1 no" "$mono_result"

printf '\n== Summary ==\n  passed: %s\n  failed: %s\n  skipped: %s\n' "$PASS" "$FAIL" "$SKIP"
[ "$FAIL" -gt 0 ] && exit 1 || exit 0
